version: '3'
services:
  backend:
    build: ./UrbanVoyageBackend
    ports:
      - "8080:8080"
  frontend:
    build: ./UrbanVoyageFrontend
    ports:
      - "80:80"
    depends_on:
      - backend